### ISSUE TITLE
*Element doesn't support percentage widths / coordinates

### ISSUE THREAD

**Issue by SammyIAm** [SergioMorchon/fitbit-sdk-types#102]
Specifically I'd like to set a `RectElement` to have a `width` of `100%`, but it's expecting only a `number`.

It doesn't seem like [Regular-expression-validated types are a thing yet](https://github.com/Microsoft/TypeScript/issues/6579), so it might require a `Percentage` class that validates the string.  Something like (forgive any typos I didn't actually try to compile this):

```
class Percentage {
	private pString:string;
	constructor(percentageString:string) {
		if (percentageString.match(/^\d+%$/g)) {
			this.pString = percentageString;
		} else {
			// throw error
		}
	}
}

interface Bounded {
	height: number | Percentage;
	width: number | Percentage;
	x: number | Percentage;
	y: number | Percentage;
}

**Comment by SergioMorchon** [comment]
Fitbit APIs mimics the DOM standard, but has its own implementation and limitations.
This projects is based in the Fitbit Development documentation.
In this case:
* [`RectElement`](https://dev.fitbit.com/build/reference/device-api/document/#interface-rectelement), which is a [`Bounded`](https://dev.fitbit.com/build/reference/device-api/document/#interface-bounded) that has defined both `height` and `width` as type `number`.

Furthermore, Fitbit pre-calculates the percentaje given in the *.gui* file and transforms it to numeric pixels. You can't manipulate percentajes in runtime (from JS). If you want that, then you have to involve the device screen size and get the number of pixels by your own.

**Comment by SammyIAm** [comment]
> Fitbit pre-calculates the percentage given in the .gui file and transforms it to numeric pixels. Indeed you can't manipulate percentages at runtime

Ah, well that would certainly be a limitation then; I didn't know that was the case.  I *had* been trying to use percentages where possible to help with compatibility for multiple devices, but a lot of things seem to be pushing me toward absolute values so I'll probably just go that way.

Thanks for the information!
