### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by fabian0150** [SergioMorchon/fitbit-sdk-types#147]
Hello Sergio,

I just wanted to ask a quick question: 

Am I able to use your SDK in my IONIC 5 project instead of a regular FitBit CLI project?

Thanks in advance, 
Fabian

**Comment by SergioMorchon** [comment]
Hi, I don't know what's your _IONIC 5_ project; this project is expected to be used through npm, and hat's only possible if you use the Fitbit CLI to build your appp / watch face
