### ISSUE TITLE
Missing definition for Section Element on Device

### ISSUE THREAD

**Issue by markmonster** [SergioMorchon/fitbit-sdk-types#158]
It seems the Section element isn't mapped yet in [elements.d.ts](https://github.com/SergioMorchon/fitbit-sdk-types/blob/master/types/device/document/elements.d.ts). I would like to make use of it though. I've never adjusted a type definition but it looks pretty straight forward.

Do you want to add this, or do you want me to create a pull request?

**Comment by SergioMorchon** [comment]
Hi @mkamonster!
I can't find any {{Section}} element in device document documentation (see https://dev.fitbit.com/build/reference/device-api/document/).
Alghouth _there is_ a {{Section}} JSX component for settings, already declared in [`settings/components.d.ts`](https://github.com/SergioMorchon/fitbit-sdk-types/blob/master/types/settings/components.d.ts#L3-L7)

**Comment by mkamonster** [comment]
Interesting. It is mentioned here: https://dev.fitbit.com/build/guides/user-interface/svg/#section .

**Comment by SergioMorchon** [comment]
Maybe the associated JS runtime prototype is something like `ContainerElement`.
That happens also with `<svg>` instances: they don't have a dedicated type like "SvgElement" or something
