### ISSUE TITLE
Body Presence and Heart Rate not working

### ISSUE THREAD

**Issue by KK-Designs** [SergioMorchon/fitbit-sdk-types#162]
I keep getting ```This expression is not constructable.
  Not all constituents of type 'void | BodyPresenceConstructor' are constructable.
    Type 'void' has no construct signatures.``` how to fix?

**Comment by SergioMorchon** [comment]
That's because the HW sensor may be or may be not available.
You must discard the `void` case, as you can see in this test code sample: https://github.com/SergioMorchon/fitbit-sdk-types/blob/master/test-code-samples/app/heart-rate/detecting-off-wrist.ts#L4

```typescript
import { BodyPresenceSensor } from 'body-presence';
import { HeartRateSensor } from 'heart-rate';

if (HeartRateSensor && BodyPresenceSensor) {
  // ...
}
```
