### ISSUE TITLE
with settings i keep getting a bunch of errors

### ISSUE THREAD

**Issue by KK-Designs** [SergioMorchon/fitbit-sdk-types#164]
![image](https://user-images.githubusercontent.com/71038229/118385336-cd71c400-b5c2-11eb-8a7e-af9f5c00d9e8.png)
 
tsconfig:
```json
{
	"extends": "../tsconfig.json",
	"include": ["../../types/settings", "**/*.tsx"]
}```

**Comment by SergioMorchon** [comment]
Hi @KK-Designs. Please, can you post the steps to reproduce from scratch?
For example with a new Fitbit CLI project and the scripts ran afterwards.

**Comment by SergioMorchon** [comment]
Indeed looks like your `tsconfig.json` isn't the same that this project provides.
Take a look at https://github.com/SergioMorchon/fitbit-sdk-types/blob/master/scripts/scaffolding/settings/tsconfig.json
