### ISSUE TITLE
More presice faq

### ISSUE THREAD

**Issue by Beat-YT** [SergioMorchon/fitbit-sdk-types#172]
Hi, i just installed the dsk and it renamed all my js files to ts.

That was okay but that made a lot of errors

![image](https://user-images.githubusercontent.com/66485277/131395594-484695d3-c142-4d47-8cce-6b972d361dd3.png)

I read the faq but its was kinda useless and empty

**Comment by SergioMorchon** [comment]
You must follow the steps described in the [Readme](https://github.com/SergioMorchon/fitbit-sdk-types#-how-to-use-in-your-app-project).

**Comment by Beat-YT** [comment]
I did

**Comment by SergioMorchon** [comment]
> I did

Then it shuold work.
If not, can you post here both the `tsconfig.json` files you have in your project, and their respective content?
