### ISSUE TITLE
installing fitbit types " SyntaxError: The requested module 'node:util' does not provide an export named 'parseArgs' "

### ISSUE THREAD

**Issue by Randle-Lanre** [SergioMorchon/fitbit-sdk-types#184]
steps to reproduce 

1.  Ran command    npx create-fitbit-app dndmytime

2. cd into dndmytime 

3. Ran npx fitbit-sdk-types install --vscode --migrate (NB: also ran the commands without the optional arguments) 

![image](https://user-images.githubusercontent.com/19264390/190393845-c31c2d83-9c74-4a1f-b4d6-3ea4e4fdef17.png)

workstation: Windows 11

NPM version: 8.16.0

Node version: 16.15.1

**Comment by SergioMorchon** [comment]
Hi @Randle-Lanre , thank you for reporting the issue, and sorry about that.
I tested it in the lates LTS, `v16.17.0`, but I don't even noticed that it was an experimental API.

**Comment by SergioMorchon** [comment]
It should be fixed in `8.0.1`.
