### ISSUE TITLE
Element.style

### ISSUE THREAD

**Issue by plaidman** [SergioMorchon/fitbit-sdk-types#57]
according to the sdk docs we should be able to modify an element's style, but it doesn't seem to be declared in the declaration files.

https://dev.fitbit.com/build/guides/user-interface/javascript/#element-styling

After looking at the code for a bit, it looks like the Element interface just needs to extend Styled. Looks like this behavior was missing from the SDK reference, but it was included in the guide. 🤷‍♂️

**Comment by SergioMorchon** [comment]
# TL; DR;

An `Element` may not be a `GraphicsElement` nor have a `style`.

# Why

It isn't as you expect there.
The `Styled` interface is available only for `GraphicsElement`s on purpose: you can get nodes from your UI that has no rendering área nor style attribute.
I'll give you a tested example:

*index.gui*
```svg
<svg>
    <defs>
        <symbol id="an-element" href="#tile-list-item" focusable="false" pointer-events="none" system-events="all" display="none">
            <text id="text" text-length="32" />
            <rect id="tile-divider-bottom" class="tile-divider-bottom" />
            <rect id="touch-me" pointer-events="all" x="0" y="0" width="100%" height="100%-2" opacity="0" />
        </symbol>
    </defs>
</svg>
```
Focus on that `symbol` element:

*app/index.ts*
```typescript
import document from "document";

let a = document.getElementById("an-element");
console.log(a.id); // logs: an-element  
// @ts-ignore
a.style.display; // fails: Unhandled TypeError: Cannot read property 'display' of undefined
```

As you can see, there is a restricted set of interfaces that are `GraphicsElement`.

**Comment by plaidman** [comment]
```js
let demo = document.getElementById('demo') as GraphicsElement;
```

I ended up doing something like this in the mean time, but you're right. I didn't think about getting non-graphical elements. Thanks for responding!
