### ISSUE TITLE
TextInput onChange callback param coming through as Object.

### ISSUE THREAD

**Issue by plaidman** [SergioMorchon/fitbit-sdk-types#58]
Regarding the onChange callback for TextInput (and possibly other TSX elements). I believe the newValue param on that callback definition has the wrong type. It's defined to be a `string` but it comes through as an object `{ 'name': <value> }`. Please let me know if this is something that should be circumvented in my code.

Thanks, and I love this project! It's made coding so much easier.

**Comment by SergioMorchon** [comment]
Looks like a bug in the SDK itself. I've posted a message about it: https://community.fitbit.com/t5/SDK-Development/Some-bugs-in-documentation-and-SDK/m-p/3208513/highlight/true#M7583

Let's see what they say!
