### ISSUE TITLE
Missing batched sensor readings

### ISSUE THREAD

**Issue by Artaud** [SergioMorchon/fitbit-sdk-types#67]
https://dev.fitbit.com/build/reference/device-api/sensors/#interface-batchedsensorreading

as well as typings for the implementations on specific sensors

**Comment by SergioMorchon** [comment]
@Artaud Take a look at, for example, [orientation batched readings test](https://github.com/SergioMorchon/fitbit-sdk-types/blob/927504b9719f4a47f7455ee7322c84fb1471d430/test-code-samples/app/orientation/batched-readings.ts).
Is that what you're looking for?

**Comment by Artaud** [comment]
I'm trying to wrap my head around this - my use case is just batched readings (don't need the non-batched) on accelerometer and heart rate sensor.

I'm using them almost exactly as in the test you've linked to, but getting the readings as numbers|null, not Float32Arrays. Actually when I tried to rewrite the typings to accommodate batches according to the Fitbit docs, I was getting Float32Array[] on each reading :)

**Comment by SergioMorchon** [comment]
So you expect a `Float32Array` instead of `number[]` or `Array<number | null>`, did I understood?
A piece of code sample would be great, just to confirm it

**Comment by Artaud** [comment]
Yes, exactly.
This is what I'm doing:

```
startSensor() {
    this.acc.onreading = () => {
        readTheReadingsArray(this.acc.readings.x, this.acc.readings.y, this.acc.readings.z)
}

readTheReadingsArray(xArr: Float32Array, yArr: Float32Array, zArr: Float32Array) {
  var res = xArr.map(function (x:number, i:number) {
    return Math.sqrt((x * x) + (yArr[i] * yArr[i]) + (zArr[i] * zArr[i]));
  })
  return scientific.max(res)
}
```

**Comment by Artaud** [comment]
My understanding is that the batchedReadings _should_ spit out Float32Arrays according to the docs https://dev.fitbit.com/build/reference/device-api/accelerometer/#interface-batchedaccelerometerreading

**Comment by SergioMorchon** [comment]
Oh I see, so #68 should fix that, as it generates `Float32Array` for `number` properties. I've Added a test with your code sample, thank you so much :D

**Comment by Artaud** [comment]
Big thanks!
