### ISSUE TITLE
Scientific

### ISSUE THREAD

**Issue by Artaud** [SergioMorchon/fitbit-sdk-types#69]
This is more of a question, but have you been able, apart from the tests, to properly use the scientific module? For some reason I can't seem to import it correctly.

If I import it as 
`import * as scientific from 'scientific'`, 
then I can use it normally (like `scientific.max(myVal)`), 
but ts linter will scream that `[ts] Property 'max' does not exist on type 'typeof import("scientific")'. [2339]`

My program will however compile and work normally, apart from the ts error.

But if I do
`import { scientific } from 'scientific' ` then I have to use the module as:
`scientific.scientific.max(myVal)`
Now ts linter is satisified, but though it does compile, scientific.scientific would be undefined at runtime.

**Comment by SergioMorchon** [comment]
I'll investigate it, because [the official doc](https://dev.fitbit.com/build/reference/device-api/signal/) is a bit confusing: it doesn't show the import in the same example as the code usage.

**Comment by Artaud** [comment]
You're a beast Sergio, it's incredible.
