### ISSUE TITLE
TickEvent isn't declared

### ISSUE THREAD

**Issue by plaidman** [SergioMorchon/fitbit-sdk-types#76]
Hi again. I can't seem to be able to use TickEvent as a type when defining a clock.ontick event handler. Am I doing it wrong?

**Comment by SergioMorchon** [comment]
You're doing it fine; they're not exposed.
But now they are required if you want to work in a `strict` TypeScript Project to define callback parameters, like in your case.
I'll review and expose them. Meanwhile, I suggest you to do it inline, so you are already type-safe:
```typesript
import clock from 'clock';

clock.addEventListener('tick', e => {// (parameter) e: TickEvent
	console.log(e.date.toTimeString());
});
// or
clock.ontick = evt => {// (parameter) evt: TickEvent
	console.log(evt.date.toTimeString());
};
```
