### ISSUE TITLE
Heart Rate Sensor Constructor

### ISSUE THREAD

**Issue by rootasjey** [SergioMorchon/fitbit-sdk-types#99]
Hi,

When I try to create a new heart rate sensor object, I got this TypeScript error:

```TypeScript
import { HeartRateSensor } from 'heart-rate'
let hrm = new HeartRateSensor() // T.S. error: Cannot use 'new' with an expression whose type lacks a call or construct signature.ts(2351)
```

When I remove the `void` union type in the `heart-rate.d.ts` definition file, the error goes away.

https://github.com/SergioMorchon/fitbit-sdk-types/blob/d8acc4fcb4eb291307a2a06024db7cefa5ff8212/types/device/heart-rate.d.ts#L18

Am I missing something ?

**Comment by SergioMorchon** [comment]
That's ok. You habe to check for HeartRate presence because it is hardware-dependant.
Take a look at https://github.com/SergioMorchon/fitbit-sdk-types/blob/master/test-code-samples/app/heart-rate/peeking-current-heart-rate.ts#L3

**Comment by rootasjey** [comment]
Oh okay. I missed that. Thank you for your answer :)
